name: ThingsBoard CI

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v4

      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Tests unitaires (modules sélectionnés)
        run: |
          mvn -B -pl common/actor,common/cache -am clean test

      - name: Lancement temporaire de ThingsBoard
        run: |
          set -e
          echo "Démarrage de ThingsBoard"
          nohup mvn -B -pl application -am spring-boot:run > /dev/null 2>&1 &
          PID=$!

          echo "Attente du démarrage de l'application"
          sleep 60

          if ! ps -p $PID > /dev/null; then
            echo "Échec du démarrage de ThingsBoard."
            exit 1
          fi

          echo "Arrêt de ThingsBoard"
          kill $PID || true
